name: django CI

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11.5]

    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
