name: grocery CI

on:
  push:
    branches: [ "development" ]
jobs:
  build:
    runs-on: ubuntu-latest
      container:
        python: 3.11
    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run Server
      run: |
        python manage.py runserver
